In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
list1 = [1,2,3]
list1

[1, 2, 3]

In [4]:
import numpy as np

In [5]:
np.array(list1)

array([1, 2, 3])

In [6]:
mat = [[1,2,3],
       [4,5,6],
       [7,8,9]]
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.zeros(2)

array([0., 0.])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.random.rand(5)

array([0.32338935, 0.86531183, 0.44049119, 0.79370488, 0.58123515])

In [11]:
np.random.randn(3)

array([ 0.44456801,  1.52983588, -1.17954652])

In [17]:
np.random.randint(0,5,10)

array([1, 2, 0, 3, 3, 3, 2, 3, 3, 2])

In [18]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
arr.max()

24

In [25]:
arr.argmax()

24

In [26]:
arr.min()

0

In [28]:
arr.dtype

dtype('int64')

In [29]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr[1:5]

array([1, 2, 3, 4])

In [32]:
arr[3] = 30
arr

array([ 0,  1,  2, 30,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr[arr > 5]

array([30,  6,  7,  8,  9, 10])

In [38]:
arr + 5

array([ 5,  6,  7, 35,  9, 10, 11, 12, 13, 14, 15])

In [42]:
arr * 10

array([  0,  10,  20, 300,  40,  50,  60,  70,  80,  90, 100])

In [43]:
arr / 10

array([0. , 0.1, 0.2, 3. , 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [44]:
arr ** 2

array([  0,   1,   4, 900,  16,  25,  36,  49,  64,  81, 100])

In [47]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743, -0.98803162, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])